SELECT
    SQL_BIG_RESULT
    id_registro, 
    rfc,
    crip,
    oficialia,
    tomo,
    tbis,
    acta,
    actaBis,
    fregistro,
    localidad,
    municipio,
    entidadf,
    nombre,
    apatern,
    amatern,
    registrado,
    sexo,
    fnacimiento,
    fnacimiento2,
    hnacimiento,
    IF((localidadnan2 like'%0%' OR localidadnan2 = '' OR localidadnan2 IS NULL OR localidadnan2 LIKE '%=%'),
    localidadnan,localidadnan2) AS localidadnan,
    IF((munnan like'%0%' OR munnan = '' OR munnan IS NULL OR munnan LIKE '%=%'),
    IF((munnan2 like'%0%' OR munnan2 = '' OR munnan2 IS NULL OR munnan2 LIKE '%=%') ,'===',munnan2),munnan) AS munnan,
    IF((pais = '' OR pais IS NULL or pais LIKE '%=%'),'MEXICANA',pais) as pais,Estado,
    nombre_padre,
    primer_ap_padre,
    segundo_ap_padre,
    edadpadre,
    nacionp,
    nombre_madre,
    primer_ap_madre,
    segundo_ap_madre,
    edadmadre,
    nacionm,
    nota,
    origen ,
	tipo_docto
FROM 
    nacimientos.consulta_n